spring:
  application:
    name: inventory-service




  zipkin:
    base-url:http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: OrderPlacedGroupId
      properties:
        spring:
          json:
            value:
              default:
                type: 'com.learntocode.notificationservice.event.OrderPlacedEvent'
            type:
              mapping: 'com.learntocode.orderservice.event.OrderPlacedEvent:com.learntocode.notificationservice.event.OrderPlacedEvent'
            trusted:
              packages: 'com.learntocode.orderservice.event'


server:
  port: 0

eureka:
  client:
    service-url:
      default zone: http://localhost:8761
  instance:
    hostname: localhost
