spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: orderserviceuser
    password: orderserviceuser

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: order-service

  zipkin:
    base-url:http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            value:
              default:
                type: 'com.learntocode.orderservice.event.OrderPlacedEvent'

server:
  port: 0

eureka:
  client:
    service-url:
      default zone: http://localhost:8761
  instance:
    hostname: localhost

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

#Resilience4j circuit-breaker properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
