Spring:
  application:
    name: discovery-server

  zipkin:
    base-url:http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


server:
  port: 8761
