spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      database: product-service
      port: 27017

server:
  port: 0


eureka:
  client:
    service-url:
      default zone: http://localhost:8761
