spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      database: product-service
      port: 27017

  zipkin:
    base-url:http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 0


eureka:
  client:
    service-url:
      default zone: http://localhost:8761
  instance:
    hostname: localhost
