spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: inventoryserviceuser
    password: inventoryserviceuser

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      default zone: http://localhost:8761